# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb73ac97af3b9bf2452febeb20ceb626d4ddaee6e3ee2d993985f4474bf5ee09dee13fd4ff2189daaba3475ce583c6dfcdafc037b7a22bed57283a15fdd498ae

test:
  secret_key_base: 0304f6823ca622864457b39f513412a7e0f65f068d6b59b38d811736ac5e4193625cf1174eb13422f4b1615d5cfe2dfabe5f94250af595d7f216f7044f74d26a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
